[project]
name = "toio.py"
version = "1.1.0"
description = "Control toio™Core Cube"
authors = [
    {name = "Sony Interactive Entertainment"},
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["toio"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
dependencies = [
    "typing-extensions>=4.10.0",
    "bleak>=3,<4",
    "setuptools>=69.5.1",
]

[project.urls]
Homepage = "https://toio.io/"
Documentation = "https://toio.github.io/toio.py/"
Repository = "https://github.com/toio/toio.py"
Issues = "https://github.com/toio/toio.py/issues"

[dependency-groups]
dev = [
    "pyright>=1.1.361",
    "isort>=5.13.2",
    "pytest>=8.2.0",
    "pytest-asyncio>=0.23.5",
    "autopep8>=2.0.2",
    "black>=24.4.2",
    "ipykernel>=6.29.3",
    "sphinx<8.0.0",
    "pytest-cov>=5.0.0",
    "coverage>=7.5.1",
    "flake8>=7.0.0",
    "mypy>=1.10.0",
    "pytest-mock>=3.12.0",
    "poethepoet>=0.26.1",
    "sphinx-rtd-theme>=2.0.0",
    "pygments>=2.17.2",
    "colorama>=0.4.6",
    "sphinx-multiversion>=0.2.4",
    "sphinx-nefertiti>=0.3.2",
    "m2r>=0.3.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["toio"]

[tool.hatch.build.targets.sdist]
exclude = [
    "/.pytest_cache/**",
    "/.ruff_cache/**",
    "/.venv/**",
    "/.vscode/**",
    "/dist/**",
    "/docs/**",
    "/**/__pycache__/**",
    "/**/*.py[cod]",
]

[tool.pyright]
ignore = ["tutorial/*"]

[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[tool.pytest.ini_options]
minversion = "6.0"
# addopts = "--cov toio --log-cli-level=INFO --import-mode=importlib"
addopts = "--log-cli-level=INFO --import-mode=importlib"
pythonpath = "toio"
testpaths = ["tests"]

[tool.mypy]
python_version = "3.10"
exclude = ["pythonista3corebluetooth"]

[tool.ruff]
line-length = 88
exclude = ["pythonista3corebluetooth"]

[tool.poe.tasks]
update-apidocs = { "shell" = "./mkdocs/mkdocs.sh --rebuild" }
check-coverage = { "shell" = "./tests/check_coverage.sh" }
